import Header from '@/components/Header';
import CV from '@/components/CV';
import Footer from '@/components/Footer';
import FooterCV from '@/components/FooterCV';
import type { Metadata } from "next";
import { EB_Garamond, Shippori_Mincho_B1 } from 'next/font/google';
import '@/styles/globals.scss';

const garamond = EB_Garamond({
  subsets: ['latin'],
  variable: '--font-garamond',
  display: 'swap',
});

const shippori = Shippori_Mincho_B1({
  subsets: ['latin'],
  weight: ['400', '700'],
  variable: '--font-shippori',
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja" className='overflow-x-hidden'>
      <body className={`${garamond.variable} ${shippori.variable} overflow-x-hidden`}>
        <div className='layout relative text-pana'>
          <Header />
          <CV />
          <main className='overflow-hidden u-main'>
            {children}
          </main>
          <FooterCV />
          <Footer />
        </div>
      </body>
    </html>
  );
}